spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: aouth2
          uri: http://localhost:8082
          predicates:
            - Path=/oauth/**
        - id: security
          uri: http://localhost:8082
          predicates:
            - Path=/security