server:
  port: 8081

spring:
  application:
    name: dynamic-router-service

#  cloud:
#    inetutils:
#      timeout-seconds: 10

  # 数据源
  redis:
    host: 39.107.230.39
    port: 16379
    password: xx$200200
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: simit200
    url: jdbc:mysql://127.0.0.1:3306/ac_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#      max-lifetime: 1800000
#      idle-timeout: 30000
#      auto-commit: true
#      pool-name: PbHikariCP
#      connection-test-query: SELECT 1
#      connection-timeout: 30000
